name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  provision_infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }}   # Injetando o key_name via variável de ambiente no terraform
      run: terraform apply -auto-approve

  deploy_application:
    needs: provision_infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build and Deploy
      run: |
        npm install
        npm run build
        zip -r MyApp.zip .
        aws deploy push --application-name MyApplication \
                        --s3-location s3://my-bucket/MyApp.zip \
                        --ignore-hidden-files
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Start AWS CodeDeploy Deployment
      run: |
        aws deploy create-deployment --application-name MyApplication \
                                     --deployment-config-name CodeDeployDefault.OneAtATime \
                                     --deployment-group-name MyDeploymentGroup \
                                     --s3-location bucket=my-bucket,key=MyApp.zip,bundleType=zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}